STAR-76 Frontend Work by Jan
fazbazjaz/star pull request #2
Opened 2023-11-19 14:18 UTC by bazmurphy

- Integrated all Frontend Work by Jan
- Made a few small adjustments

2023-11-19 16:32 UTC, softacoder requested changes
Ok. I see the index.html has not used the updates I did for google maps. 
<img width="1440" alt="Screenshot 2023-11-19 at 16 29 31" src="https://github.com/fazbazjaz/star/assets/113185323/d8593abd-a7f1-4012-b933-971a43cce3d2">.  Check for more comments.

2023-11-19 19:54 UTC, bazmurphy commented
> Ok. I see the index.html has not used the updates I did for google maps.

@softacoder 

Instead of us loading the google maps api globally I adjusted it so it loads it only when the Map component loads.

It still works in the same sort of way to before, just a slightly different/optimised implementation

2023-11-20 14:24 UTC, softacoder submitted a review, later dismissed
Ok. I see the index.html has not used the updates I did for google maps. 
<img width="1440" alt="Screenshot 2023-11-19 at 16 29 31" src="https://github.com/fazbazjaz/star/assets/113185323/d8593abd-a7f1-4012-b933-971a43cce3d2">.  Check for more comments.

2023-11-20 14:24 UTC, softacoder commented on client/src/pages/Home.jsx
As you read before in the previous repos there were no Home.jsx. so i have not worked in this one. But just remember if you check with localhost the map is not visible and I guess this is the new path to our landing page? Since I designed it so the map would only display on the landing page I suggest we put the code for map in Home.jsx and also put in the google path into index.html. Once that is done it will work. That would mean we delete the Map.jsx but use the code from there to put into Home.jsx and index.html. I dont have a problem with using a Map.jsx but I think the map would display on all pages - even the ones when we are loggedin.

2023-11-20 14:24 UTC, softacoder commented on client/src/components/Header.jsx
The code in the header we used in the previous repos was different compared to the latest. (Check in localhost). On that one I had changed the text to STAR by CodeYourFuture, it had a background color light peach and a CYF logo to the left. I used space evenly and so on. I have the code saved in notes. The question is what goes fastest for the team? Is it me going in and do some of the updates again. The same applies for the Footer.jsx.
<img width="1440" alt="Screenshot 2023-11-20 at 13 27 55" src="https://github.com/fazbazjaz/star/assets/113185323/b5dae3b2-4ebd-4d5f-9766-c5125ef07c4f">

2023-11-20 14:24 UTC, softacoder commented on client/src/components/Footer.jsx
In general when it comes to this PR the code changes made here is relevant to the previous code we had in the first repo. So when we look at localhost then all looked great. In our latest repo the code base is different so when i now look in localhost it will not be the same. 
When i look in localhost now there are no changes of mine in localhost and the Footer.jsx. I have saved the code in notes so i can paste it in. Or is it important for Faz to do code the migration again? The start with different repos was a little bit messy so how do you prefer to do this?

2023-11-20 14:24 UTC, softacoder commented on client/index.html
In my previous repo I have code here to get a path to Google map and I placed it at the bottom of the code.

2023-11-20 15:48 UTC, bazmurphy commented
## Map

- the google maps api only needs to be on the Home Page

- React uses a nested structure
- There is a Hierarchy
- App > Layout > Home > 

- And inside the Home Page... is the various Components that makeup the Home Page eg. Hero, and then Map 

- This is the React way of structuring things

- I extracted your Map logic from the Hero and put it in a separate Map Component
- That Map component can be used dynamically anywhere

- Injecting the Google Maps JS API directly into the index.html is not good practice when it is not used on all of the pages, so I instead used a package and dynamically load it whenever the Map component is needed and unload it when it is not. Optimisation.

## Header

- The Header - Farzaneh and I went over the last project together, and we decided the SideBar has to go FOR NOW (it can come back later) because we were trying to get the Project into the correct state. Her team built that previously and they didn't do a great job tbh.
- We can make a new ticket around a SideBar at a later date.
- The Header text can be easily adjusted, but if you have quite long text in a Header it becomes questionable UX/UI

## Footer

- The Footer I kept the same except for just adjusting things for when we start using Material UI Themes/Palletes etc. The structure is the same the only thing is the background color/text color changes which are very minor. We will choose a Theme/Pallete together and it will globally apply itself to all the Material UI Components if we make sure to code them properly.

## About Page

- I kept all the content you did I just improved the structure and nesting a little bit to allow more dynamic resizing later on.

## Navigation

- This was created by me when re-doing the whole Repo because I needed to test the Authentication I made. It is not designed to be final or perfect. It was made to be a functional test. Again this can be improved upon, or possibly even binned later.

2023-11-20 18:35 UTC, jarrodruby approved these changes

2023-11-20 18:46 UTC, merged